{
 "title": "Eth Exporter Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "RPC Calls duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (method) (rate(rpc_calls_duration_seconds_sum[8m]))) / (sum by (method) (rate(rpc_calls_duration_seconds_count[8m])))",
     "legendFormat": "avg_{{method}}"
    },
    {
     "expr": "sum by (method) (histogram_quantile(0.9, rate(rpc_calls_duration_seconds_bucket[8m])))",
     "legendFormat": "p90_{{method}}"
    }
   ]
  },
  {
   "title": "RPC Calls by Method (/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by (method) (rate(rpc_calls_duration_seconds_count[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(block_processing_duration_seconds_sum[8m]) / rate(block_processing_duration_seconds_count[8m])",
     "legendFormat": "avg"
    },
    {},
    {
     "expr": "histogram_quantile(0.9, rate(block_processing_duration_seconds_bucket[8m]))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "RPC Calls in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (rpc_calls_in_flight)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}