services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus-grafana/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./prometheus-grafana/grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./prometheus-grafana/grafana/provisioning/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./prometheus-grafana/grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  prom_data:
