calls:
  # A call that generates several metrics from a struct
  - contract_type: SignedBucketRiskModule
    function: params
    addresses: &riskmodules  # we'll perform the same call on all these addresses
      - RM_BIZAWAY_BMA
      - RM_BLI
    metrics: # this function returns a struct, we map each value of interest to a metric
      moc:
        type: GAUGE
        description: Margin of conservativism
        name: rm_moc
      jrCollRatio:
        type: GAUGE
        description: Jr collateralization ratio
        name: rm_jr_coll_ratio

  - contract_type: SignedBucketRiskModule
    function: activeExposure
    addresses: *riskmodules
    metrics:
      activeExposure:
        type: GAUGE
        description: Active exposure
        name: rm_active_exposure

  # A call that generates a single metric from a scalar value
  - &usdce_balance
    contract_type: IERC20
    function: balanceOf
    arguments:
      - value: CF_LENDER_KOALA_VAULT
        type: address
        label: holder
    addresses:
      - USDC
    metrics:
      balance:
        type: GAUGE
        description: USDC.e balance
        name: usdce_balance
  - <<: *usdce_balance
    arguments:
      - value: CF_LENDER_BLI
        type: address
        label: holder
  - <<: *usdce_balance
    arguments:
      - value: CF_LENDER_GETSPOT
        type: address
        label: holder
